spring:
  profiles:
    active: dev
  datasource:
    hikari:
      maximum-pool-size: 4
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com

logging:
  level:
    root: info
    com.api.trip: debug