spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  jpa:
    hibernate:
      show_sql: true
    open-in-view: false

logging:
  level:
    root: info
    com.api.trip: debug
