spring:
  profiles:
    active: dev
  datasource:
    hikari:
      maximum-pool-size: 4
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
  data:
    web:
      pageable:
        one-indexed-parameters: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

logging:
  level:
    root: info
    com.api.trip: debug